      version: '3.7'

      services:
        zookeeper:
          image: wurstmeister/zookeeper
          container_name: zookeeper
          ports:
            - "2181:2181"
          networks:
            - kafka-net

        kafka:
          image: wurstmeister/kafka
          container_name: kafka
          ports:
            - "9092:9092"
          depends_on:
            - zookeeper
          environment:
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-container:9092
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
            KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
            KAFKA_CREATE_TOPICS: "alphavantage-data:1:1,polygon-data:1:1"
          networks:
            - kafka-net

      networks:
        kafka-net:
          driver: bridge

          
